language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install:
  - composer update --no-interaction --prefer-source
  - composer info -i

script:
- ./vendor/bin/phpunit --configuration tests/phpunit.xml
